project:
  type: website
  output-dir: docs

website:
  title: "nearctic-odonate-wings-analysis"
  navbar:
    left:
      - href: index.qmd
        text: About
      - data_prep.qmd
      - descriptive.qmd
      - modeling.qmd
      - publication_figures.qmd
      - supplemental.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

