---
title: "Models"
---

Load packages for modeling

```{r, message=FALSE,warning=FALSE}

library(phyr)
library(lme4)
library(sjPlot)
library(performance)
library(dplyr)
library(glmmTMB)
library(tidyr)
library(sjPlot)
library(marginaleffects)
```

Scale variables

```{r}

wings$temp_indv_sc <- scale(wings$temp_indv)
wings$Area_total <- wings$Area.FW..mm2. + wings$Area.HW..mm2.
wings$Area_total_sc <- scale(wings$Area_total)
```

Drop observations missing any of these variables

```{r}

wings2 <- wings %>% drop_na(Sex,temp_indv_sc, flight_type, black, Area_total, mean_lightness)
```

Describe what this is doing Rob?

```{r}

wings4 <- bind_rows(
  wings2 %>%
    group_by(flight_type) %>%
    filter(flight_type=="flyer"),
  wings2 %>%
    group_by(Sex) %>%
    filter(flight_type=="percher") %>%
    slice_sample(n = 1000))
```

Model

```{r}

m4 <- glmmTMB(black ~ (flight_type * Sex) + temp_indv_sc + (1 | species),
              data=wings4, family=beta_family(link="logit"),
              ziformula = ~., na.action = "na.fail")
summary(m4)
plot_predictions(m4, type="conditional", condition = list("flight_type","Sex")) + xlab("Scaled wing area") + ylab#("Proportion of brown color cluster in wing")

```
